[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#38bdf8"
backgroundColor = "#080c14"
secondaryBackgroundColor = "#0c111d"
textColor = "#f1f5f9"
font = "sans serif"

[client]
showErrorDetails = true

